### ISSUE TITLE
Bold italic with "CMU Serif bold extended italic" and not "CMU Serif bold italic"

### ISSUE THREAD

**Issue by galvanetto** [Binjohn/cm-unicode-msofix#2]
Thank you for this fix. In my case I can make the bold italic only typing "CMU Serif bold extended italic" in the font menu.
Moreover, I don't find these font names (bold, italic, etc) in the menu (indeed I was surprised that I was typing a name not present in the list and it worked).

**Comment by Binjohn** [comment]
I think you should set the font to "CMU Serif" and push the "Bold" and "Italic" buttons on the toolbar.
Word will apply the correct font by itself.  Users do not need to type the specific font name by hand.
This worked for me in Word 2016. Would you please give it a try?

The font names were made by the original creator.
I know it is strange to have "Extended" there, but if it just works, I tend to leave them untouched.

**Comment by galvanetto** [comment]
I commfirm that now the behavior is as you say
